# Generated by Django 4.2.2 on 2023-12-01 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'User Information',
            },
        ),
        migrations.CreateModel(
            name='UserNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=500)),
                ('note_label', models.CharField(blank=True, max_length=5000, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserData.userinfo')),
            ],
            options={
                'verbose_name': 'User Notes',
            },
        ),
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='UserNotePictures/')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='UserData.usernotes')),
            ],
            options={
                'verbose_name': 'Notes Image',
            },
        ),
    ]
