# Generated by Django 4.2.7 on 2023-11-27 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='UserNotePictures/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserData.userinfo')),
            ],
            options={
                'verbose_name': 'User Notes',
            },
        ),
    ]
