# Generated by Django 4.2.2 on 2023-12-01 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes_Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelName', models.CharField(max_length=100)),
                ('label_for', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='UserData.userinfo')),
            ],
            options={
                'verbose_name': 'Notes Label',
            },
        ),
    ]
