# Generated by Django 4.2.2 on 2023-11-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0002_usernotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotes',
            name='image',
        ),
    ]
