# Generated by Django 4.2.2 on 2023-12-01 14:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0003_alter_usernotes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
