# Generated by Django 4.2.2 on 2023-11-30 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0003_remove_usernotes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='UserNotePictures/')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserData.usernotes')),
            ],
            options={
                'verbose_name': 'Notes Images',
            },
        ),
    ]
