# Generated by Django 4.2.2 on 2023-12-01 14:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0004_alter_usernotes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
