# Generated by Django 4.2.2 on 2023-12-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0007_alter_usernotes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
