# Generated by Django 4.2.2 on 2023-12-02 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0009_alter_usernotes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
