# Generated by Django 4.2.2 on 2023-12-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0010_usernotes_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotes',
            name='date',
        ),
    ]
